apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-secret-reader
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
